version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
      - redis
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/healthz"]
      interval: 10s
      timeout: 3s
      retries: 10

  qdrant:
    image: qdrant/qdrant:v1.15.3   # pin to stable version
    ports:
      - "6333:6333"
    volumes:
      - qdrant-data:/qdrant/storage
    # disable strict healthcheck to avoid blocking api
    healthcheck:
      test: ["CMD", "true"]

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: [
      "redis-server", 
      "--save", "", 
      "--appendonly", "no",
      "--maxmemory", "512mb",
      "--maxmemory-policy", "allkeys-lru",
      "--tcp-keepalive", "60",
      "--timeout", "30",
      "--tcp-backlog", "1024",
      "--databases", "16",
      "--maxclients", "1000"
    ]
    sysctls:
      - net.core.somaxconn=1024

volumes:
  qdrant-data: