name: Web UI CI

on:
  push:
    paths:
      - 'web/**'
      - '.github/workflows/ui.yml'
  pull_request:
    paths:
      - 'web/**'
      - '.github/workflows/ui.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json
      
      - name: Install dependencies
        run: |
          cd web
          npm ci
      
      - name: Type check
        run: |
          cd web
          npm run type-check
      
      - name: Lint
        run: |
          cd web
          npm run lint
      
      - name: Run tests
        run: |
          cd web
          npm run test:run
      
      - name: Build
        run: |
          cd web
          npm run build

  e2e:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json
      
      - name: Install dependencies
        run: |
          cd web
          npm ci
      
      - name: Install Playwright browsers
        run: |
          cd web
          npx playwright install --with-deps
      
      - name: Run E2E tests
        run: |
          cd web
          npm run test:e2e
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: web/playwright-report/
          retention-days: 30

  build-docker:
    runs-on: ubuntu-latest
    needs: [test, e2e]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.web
          push: false
          tags: rag-web:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max 